# Generated by Django 5.2.4 on 2025-11-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasajero",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
