# Generated by Django 5.2.4 on 2025-11-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_alter_pasajero_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
