# Generated by Django 5.2.4 on 2025-11-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_pasajero_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='nacionalidad',
        ),
    ]
