# Generated by Django 5.2.4 on 2025-07-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('PAS', 'Pasaporte'), ('LC', 'Libreta Cívica'), ('LE', 'Libreta de Enrolamiento')], max_length=10)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
