# Generated by Django 5.2.4 on 2025-07-31 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasajero',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Pasajero', 'verbose_name_plural': 'Pasajeros'},
        ),
    ]
