# Generated by Django 5.2.4 on 2025-07-31 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0002_alter_pasajero_options'),
        ('reservas', '0001_initial'),
        ('vuelos', '0002_pasajero_alter_asiento_options_alter_avion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boleto',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_desde_reservas_app', to='vuelos.asiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_vuelos', to='pasajeros.pasajero'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_desde_reservas_app', to='vuelos.vuelo'),
        ),
    ]
