# Generated by Django 5.2.4 on 2025-07-31 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0002_alter_pasajero_options'),
        ('reservas', '0002_alter_boleto_options_alter_reserva_options_and_more'),
        ('vuelos', '0004_remove_reserva_pasajero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelos.asiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pasajeros.pasajero'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelos.vuelo'),
        ),
    ]
