# Generated by Django 5.2.4 on 2025-07-31 00:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('cedula', 'Cédula')], default='dni', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
            },
        ),
        migrations.AlterModelOptions(
            name='asiento',
            options={'ordering': ['fila', 'columna'], 'verbose_name': 'Asiento', 'verbose_name_plural': 'Asientos'},
        ),
        migrations.AlterModelOptions(
            name='avion',
            options={'verbose_name': 'Avión', 'verbose_name_plural': 'Aviones'},
        ),
        migrations.AlterModelOptions(
            name='vuelo',
            options={'ordering': ['fecha_salida'], 'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('avion', 'numero')},
        ),
        migrations.AlterField(
            model_name='asiento',
            name='columna',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('primera', 'Primera Clase'), ('ejecutiva', 'Clase Ejecutiva'), ('economica', 'Clase Económica')], default='economica', max_length=20),
        ),
        migrations.AlterField(
            model_name='avion',
            name='capacidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='avion',
            name='columnas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='avion',
            name='filas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.avion'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('abordando', 'Abordando'), ('en_vuelo', 'En Vuelo'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_reserva', models.CharField(blank=True, max_length=10, unique=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_desde_vuelos_app', to='vuelos.asiento')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_vuelos', to='vuelos.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_desde_vuelos_app', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('vuelo', 'asiento')},
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('usado', 'Usado'), ('cancelado', 'Cancelado')], default='emitido', max_length=20)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vuelos.reserva')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='estado',
        ),
    ]
