# Generated by Django 5.2.4 on 2025-07-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_pasajero_alter_asiento_options_alter_avion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='columna',
            field=models.CharField(max_length=1),
        ),
    ]
