# Generated by Django 5.2.4 on 2025-07-31 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_asiento_estado_alter_asiento_columna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pasajero',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='asiento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='vuelo',
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='columna',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('economico', 'Económico'), ('ejecutivo', 'Ejecutivo'), ('primera', 'Primera Clase')], default='economico', max_length=20),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vuelos.avion'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado'), ('retrasado', 'Retrasado')], default='programado', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('avion', 'fila', 'columna')},
        ),
        migrations.DeleteModel(
            name='Boleto',
        ),
        migrations.DeleteModel(
            name='Pasajero',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
